[api]
enabled = true
bind = ":8000"

[logging]
level = "info"
output = "stdout" 

#
[defaults]
max_connections = 0
client_idle_timeout = "0" 
backend_idle_timeout = "0"
backend_connection_timeout = "0"
china_ipdb_path = "/run/media/millken/09a7d751-1ed0-48f0-9240-c67c262700dd/go/src/github.com/millken/go-ipdb/dbv2.dat"

[servers]


[servers.sample]
protocol = "tcp"
bind = "localhost:1880"
upstream = [
      "localhost:80",
  ]
max_connections = 80
#per_ip_connections = 5
limit_china_access_default = "deny"
filter_request_content_default = "allow"

[servers.sample.limit_reconnect_rate]
interval = "3s"
reconnects = 23333

[servers.sample.limit_per_ip_rate]
interval = "1s"
readbytes = 10000
writebytes = 5000

[[servers.sample.limit_china_access]]
isp = "ip-lt"
access = "deny"
[[servers.sample.limit_china_access]]
isp = "ip-lt"
region="rn-beijing"
access = "allow"

[[servers.sample.filter_request_content]]
mode = "hex"
content = "48545450"
access = "deny"
